// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Currency string

const (
	CurrencyNGN Currency = "NGN"
	CurrencyUSD Currency = "USD"
)

func (e *Currency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Currency(s)
	case string:
		*e = Currency(s)
	default:
		return fmt.Errorf("unsupported scan type for Currency: %T", src)
	}
	return nil
}

type NullCurrency struct {
	Currency Currency
	Valid    bool // Valid is true if Currency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrency) Scan(value interface{}) error {
	if value == nil {
		ns.Currency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Currency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Currency), nil
}

type LedgerEntryType string

const (
	LedgerEntryTypeDebit  LedgerEntryType = "debit"
	LedgerEntryTypeCredit LedgerEntryType = "credit"
)

func (e *LedgerEntryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerEntryType(s)
	case string:
		*e = LedgerEntryType(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerEntryType: %T", src)
	}
	return nil
}

type NullLedgerEntryType struct {
	LedgerEntryType LedgerEntryType
	Valid           bool // Valid is true if LedgerEntryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerEntryType) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerEntryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerEntryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerEntryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerEntryType), nil
}

type TransactionStatus string

const (
	TransactionStatusPending TransactionStatus = "pending"
	TransactionStatusSuccess TransactionStatus = "success"
	TransactionStatusFailed  TransactionStatus = "failed"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus
	Valid             bool // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type TransactionType string

const (
	TransactionTypeTransfer   TransactionType = "transfer"
	TransactionTypeDeposit    TransactionType = "deposit"
	TransactionTypeWithdrawal TransactionType = "withdrawal"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType
	Valid           bool // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusDeleted   UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type WalletStatus string

const (
	WalletStatusActive WalletStatus = "active"
	WalletStatusFrozen WalletStatus = "frozen"
	WalletStatusClosed WalletStatus = "closed"
)

func (e *WalletStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletStatus(s)
	case string:
		*e = WalletStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletStatus: %T", src)
	}
	return nil
}

type NullWalletStatus struct {
	WalletStatus WalletStatus
	Valid        bool // Valid is true if WalletStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WalletStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletStatus), nil
}

type LedgerEntry struct {
	ID            pgtype.UUID
	TransactionID pgtype.UUID
	WalletID      pgtype.UUID
	EntryType     LedgerEntryType
	Amount        int64
	Currency      Currency
	CreatedAt     pgtype.Timestamptz
}

type Session struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	TokenFamilyID pgtype.UUID
	TokenHash     string
	Used          bool
	Revoked       bool
	DeviceID      pgtype.Text
	IpAddress     *netip.Addr
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type Transaction struct {
	ID                  pgtype.UUID
	Type                TransactionType
	Status              TransactionStatus
	Amount              int64
	Currency            Currency
	SourceWalletID      pgtype.UUID
	DestinationWalletID pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UserID              pgtype.UUID
	IdempotencyKey      string
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Phone        pgtype.Text
	PasswordHash string
	Role         string
	KycTier      int16
	Status       UserStatus
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Wallet struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Currency  Currency
	Status    WalletStatus
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WalletBalance struct {
	WalletID         pgtype.UUID
	AvailableBalance int64
	HeldBalance      int64
	UpdatedAt        pgtype.Timestamptz
}
