// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id,
    user_id,
    idempotency_key,
    type,
    status,
    amount,
    currency,
    source_wallet_id,
    destination_wallet_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (user_id, idempotency_key)
DO NOTHING
RETURNING
    id,
    user_id,
    idempotency_key,
    type,
    status,
    amount,
    currency,
    source_wallet_id,
    destination_wallet_id,
    created_at
`

type CreateTransactionParams struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	IdempotencyKey      string
	Type                TransactionType
	Status              TransactionStatus
	Amount              int64
	Currency            Currency
	SourceWalletID      pgtype.UUID
	DestinationWalletID pgtype.UUID
}

type CreateTransactionRow struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	IdempotencyKey      string
	Type                TransactionType
	Status              TransactionStatus
	Amount              int64
	Currency            Currency
	SourceWalletID      pgtype.UUID
	DestinationWalletID pgtype.UUID
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.UserID,
		arg.IdempotencyKey,
		arg.Type,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.SourceWalletID,
		arg.DestinationWalletID,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.SourceWalletID,
		&i.DestinationWalletID,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT
    id,
    user_id,
    idempotency_key,
    type,
    status,
    amount,
    currency,
    source_wallet_id,
    destination_wallet_id,
    created_at
FROM transactions
WHERE id = $1
`

type GetTransactionByIDRow struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	IdempotencyKey      string
	Type                TransactionType
	Status              TransactionStatus
	Amount              int64
	Currency            Currency
	SourceWalletID      pgtype.UUID
	DestinationWalletID pgtype.UUID
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.SourceWalletID,
		&i.DestinationWalletID,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT
    id,
    user_id,
    idempotency_key,
    type,
    status,
    amount,
    currency,
    source_wallet_id,
    destination_wallet_id,
    created_at
FROM transactions
WHERE user_id = $1
  AND idempotency_key = $2
`

type GetTransactionByIdempotencyKeyParams struct {
	UserID         pgtype.UUID
	IdempotencyKey string
}

type GetTransactionByIdempotencyKeyRow struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	IdempotencyKey      string
	Type                TransactionType
	Status              TransactionStatus
	Amount              int64
	Currency            Currency
	SourceWalletID      pgtype.UUID
	DestinationWalletID pgtype.UUID
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, arg GetTransactionByIdempotencyKeyParams) (GetTransactionByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, arg.UserID, arg.IdempotencyKey)
	var i GetTransactionByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.SourceWalletID,
		&i.DestinationWalletID,
		&i.CreatedAt,
	)
	return i, err
}
