// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet_balances.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWalletBalanceForUpdate = `-- name: GetWalletBalanceForUpdate :one
SELECT
    wallet_id,
    available_balance,
    held_balance,
    updated_at
FROM wallet_balances
WHERE wallet_id = $1
FOR UPDATE
`

func (q *Queries) GetWalletBalanceForUpdate(ctx context.Context, walletID pgtype.UUID) (WalletBalance, error) {
	row := q.db.QueryRow(ctx, getWalletBalanceForUpdate, walletID)
	var i WalletBalance
	err := row.Scan(
		&i.WalletID,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.UpdatedAt,
	)
	return i, err
}
