// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
    id,
    user_id,
    currency
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    user_id,
    currency,
    status,
    created_at,
    updated_at
`

type CreateWalletParams struct {
	ID       pgtype.UUID
	UserID   pgtype.UUID
	Currency Currency
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.ID, arg.UserID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletForUpdate = `-- name: GetWalletForUpdate :one
SELECT
    id,
    user_id,
    currency,
    status
FROM wallets
WHERE id = $1
FOR UPDATE
`

type GetWalletForUpdateRow struct {
	ID       pgtype.UUID
	UserID   pgtype.UUID
	Currency Currency
	Status   WalletStatus
}

func (q *Queries) GetWalletForUpdate(ctx context.Context, id pgtype.UUID) (GetWalletForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getWalletForUpdate, id)
	var i GetWalletForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Status,
	)
	return i, err
}
